# Generated by Django 4.1.3 on 2022-11-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_friends1_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends1',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userapp.users'),
        ),
        migrations.AlterField(
            model_name='friends1',
            name='users1',
            field=models.ManyToManyField(to='userapp.users'),
        ),
    ]
