# Generated by Django 4.1.3 on 2022-11-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_friends1_current_user_alter_friends1_users1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='comments',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='LikesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('comments', models.TextField(max_length=10000)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.users')),
            ],
        ),
    ]
