# Generated by Django 4.1.3 on 2022-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_resource_comments_resource_likes_likescomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likescomments',
            name='comments',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
