# Generated by Django 4.1.3 on 2022-11-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_likescomments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likescomments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likescomments',
            name='user',
        ),
        migrations.AddField(
            model_name='likescomments',
            name='user',
            field=models.ManyToManyField(to='userapp.users'),
        ),
    ]
