# Generated by Django 4.1.3 on 2022-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_likescomments_likes_remove_likescomments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='likes',
        ),
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.ManyToManyField(blank=True, to='userapp.users'),
        ),
    ]
