# Generated by Django 4.1.3 on 2022-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_resource_likes_resource_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_like', to='userapp.users'),
        ),
    ]
