# Generated by Django 4.1.3 on 2022-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_resource_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='countLikes',
            field=models.IntegerField(default=0),
        ),
    ]
