# Generated by Django 4.1.3 on 2022-11-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_resource_countlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likescomments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='likescomments',
            name='user',
        ),
        migrations.AddField(
            model_name='likescomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.users'),
        ),
    ]
