# Generated by Django 4.1.3 on 2022-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_likescomments_likes_remove_likescomments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likescomments',
            name='user',
        ),
        migrations.AddField(
            model_name='likescomments',
            name='user',
            field=models.ManyToManyField(to='userapp.users'),
        ),
    ]
