# Generated by Django 4.1.3 on 2022-11-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_likescomments_resource_likescomments_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likescomments',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='likescomments',
            name='user',
        ),
        migrations.AddField(
            model_name='likescomments',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.resource'),
        ),
        migrations.AddField(
            model_name='likescomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.users'),
        ),
    ]
