# Generated by Django 4.1.3 on 2022-11-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_likescomments_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='likes',
        ),
    ]
