# Generated by Django 4.1.3 on 2022-11-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_resource_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=10000, null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.users')),
            ],
        ),
    ]
