# Generated by Django 4.1.3 on 2022-11-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_resource_comments_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesComments',
        ),
    ]
