# Generated by Django 4.1.3 on 2022-11-28 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_delete_likescomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comments',
        ),
        migrations.AlterField(
            model_name='resource',
            name='countLikes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
