# Generated by Django 4.1.3 on 2022-11-28 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_remove_like_comments_alter_resource_countlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='countLikes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
