# Generated by Django 4.1.3 on 2022-11-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_alter_membership_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='invite_reason',
        ),
    ]
