# Generated by Django 4.1.3 on 2022-11-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_grouprequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
