# Generated by Django 4.1.3 on 2022-11-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_rename_group_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.groups'),
        ),
    ]
