# Generated by Django 4.1.3 on 2022-11-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_resource_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user_id',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.users'),
        ),
    ]
