# Generated by Django 4.1.3 on 2022-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_remove_resource_user_id_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ManyToManyField(to='userapp.users'),
        ),
    ]
