# Generated by Django 4.1.3 on 2022-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_remove_resource_user_resource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='haha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='wow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='haha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='wow',
            field=models.IntegerField(default=0),
        ),
    ]
