# Generated by Django 4.1.3 on 2022-12-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_like_angry_like_care_like_haha_like_love_like_sad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='angry',
        ),
        migrations.RemoveField(
            model_name='like',
            name='care',
        ),
        migrations.RemoveField(
            model_name='like',
            name='haha',
        ),
        migrations.RemoveField(
            model_name='like',
            name='love',
        ),
        migrations.RemoveField(
            model_name='like',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='like',
            name='wow',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='angry',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='care',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='haha',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='love',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='wow',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='leader',
        ),
        migrations.AddField(
            model_name='groups',
            name='leader',
            field=models.ManyToManyField(related_name='leader', to='userapp.users'),
        ),
    ]
