# Generated by Django 4.1.3 on 2022-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_remove_like_angry_remove_like_care_remove_like_haha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends1',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
