# Generated by Django 4.1.4 on 2022-12-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_friends1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends1',
            name='status',
        ),
    ]
